one

diff --git a/.github/workflows/first.yml b/.github/workflows/first.yml
--- a/.github/workflows/first.yml
+++ b/.github/workflows/first.yml
@@ -1,15 +1,49 @@
-name: first
-on: push
+
+name: Test Action
+on: [push]
+
 jobs:
-  generate-a-secret-output:
+  test:
     runs-on: ubuntu-latest
     steps:
-    - name: Set the value
-      id: step_one
-      run: |
-        echo "action_state=yellow" >> "$GITHUB_ENV"
-    - run: |
-        echo "${{ env.action_state }}" # This will output 'yellow'
+      - name: Checkout repo to use the action locally
+        uses: actions/checkout@v3.5.3
+        
+      - name: Run my own container action
+        id: action
+        uses: ./
+        with:
+          who-to-greet: '@wulfland'
+      
+      - name: Output the answer
+        run: echo "The answer is ${{ steps.action.outputs.answer }}"
+      
+      - name: Test the container
+        if: ${{ steps.action.outputs.answer != 42 }}
+        run: |
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
+
+
+
+
+
+
+
+
+
+# name: first
+# on: push
+# jobs:
+#   generate-a-secret-output:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Set the value
+#       id: step_one
+#       run: |
+#         echo "action_state=yellow" >> "$GITHUB_ENV"
+#     - run: |
+#         echo "${{ env.action_state }}" # This will output 'yellow'
     # - id: sets-a-secret
     #   name: Generate, mask, and output a secret
     #   run: |
